title: My Portfolio
description: A showcase of my work and blog
url: https://your-portfolio-url.com
author: Your Name
theme: minimal
paginate: 5
markdown: kramdown
permalink: pretty
social:
  twitter: your_twitter_handle
  github: your_github_username
  linkedin: your_linkedin_profile
tags:
  - portfolio
  - blog
  - personal
  - projects
  - development